[package]
name = "event-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
ethers = { version = "2.0", features = ["legacy"]}
