[package]
name = "state_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = { version = "1.37", features = ["full"]}
tracing = "0.1"
tracing-subscriber = "0.3"